### PR TITLE
chunk objects when uploading via PutObject

### LINKED ISSUE #26: Azure blob storage backups larger than 256MiB fail due to RequestBodyTooLarge Error
**What steps did you take and what happened:**

When running backups to Azure blob storage from a large cluster, the backup fails with the following error:

```
time="2020-02-25T22:08:02Z" level=error msg="backup failed" controller=backup error="rpc error: code = Unknown desc = storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.\nRequestId:9a1043dc-601e-005f-7828-ecd157000000\nTime:2020-02-25T22:08:02.6045264Z, RequestInitiated=Tue, 25 Feb 2020 22:08:02 GMT, RequestId=9a1043dc-601e-005f-7828-ecd157000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=" key=velero/hourly-k8s-backup-20200225220036 logSource="pkg/controller/backup_controller.go:233"
```

**What did you expect to happen:**

Backups should succeed

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

See above

**Anything else you would like to add:**

~~Apparently there is a 4MB chunk limit with Azure Blob Store, and chunking is required above 4MB: https://support.microsoft.com/en-us/help/4016806/the-request-body-is-too-large-error-when-writing-data-to-azure-file~~ This specific document was for Azure File and not Blob Store, see comment below

**Environment:**

- Velero version (use `velero version`): 1.1.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`): 1.16.7
- Kubernetes installer & version: custom
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`): CoreOS Container Linux

### PR DESCRIPTION
**Pull request by skriss**
closes #26 

I've pushed a dev image containing this change to `steveheptio/velero-plugin-for-microsoft-azure:chunk-objects`.

### CODE REVIEW

**Comment by skriss** [comment]
@dharmab I'm not sure if you have an environment where you're comfortable testing out a patch, but I've pushed a dev image containing this change (https://github.com/vmware-tanzu/velero-plugin-for-microsoft-azure/pull/30#issue-383904968). It's seemed to work well in my testing but would be great to get additional eyes.

If you do have an environment where you can test this, you can either `kubectl -n velero edit deploy/velero` and change the image for the plugin init container, or you can do:

```bash
velero plugin remove velero/velero-plugin-for-microsoft-azure:v1.0.0 # change the version tag if you've already upgraded to v1.0.1
velero plugin add steveheptio/velero-plugin-for-microsoft-azure:chunk-objects
```

**Comment by dharmab** [comment]
@skriss I'll be able to test this within 24 hours.

**Comment by dharmab** [comment]
I've upgraded my impacted cluster to Velero 1.2 and will test this PR there.

**Comment by dharmab** [comment]
I deployed the plugin and ran a test backup, which failed without logging any errors:

```
[kube]$ velero backup get dharmab-test-2
NAME             STATUS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
dharmab-test-2   Failed   2020-03-05 14:03:48 -0700 MST   6d        default            <none>
[kube]$ velero backup logs dharmab-test-2 | grep -v "level=info"
[kube]$
```

The log content is somewhat sensitive so I cannot post it publicly, but it just contained the standard info logs about the items it was backup up.

**Comment by skriss** [comment]
Hmm. Are there any errors in the server log (e.g. `kubectl -n velero logs deploy/velero | grep error`)?

**Comment by skriss** [comment]
@dharmab can you find in the server logs from around where the backup finished running? Any info from that would be helpful for tracking this down.

I'll try some more tests and see if I can figure out what's happening too

**Comment by skriss** [comment]
I wonder if you're running into pod resource issues - do you have CPU/mem requests/limits set for the velero pod?

It's possible the chunks need to be smaller, since this is reading 100MB at a time which could be pushing past memory limits.

**Comment by dharmab** [comment]
Pod resource limits aren't the issue- we had to raise our limits very high due to https://github.com/vmware-tanzu/velero/issues/2069, which was only fixed in 1.3.0 a few days ago.

I'll see if I can create a reproducible case with a script to create a few thousand configmaps or something.

**Comment by skriss** [comment]
OK; I did further testing and was unable to reproduce so any additional info you can provide from the logs, etc. will be very helpful for figuring this out.

**Comment by dharmab** [comment]
I was able to reproduce and test this successfully with Velero 1.3. I think the mentioned memory leak in Velero 1.2 tainted the result.

Steps to reproduce:

```
dd if=/dev/urandom bs=1024 count=256 of=256k-padding.txt
kubectl create namespace velero-azure-issue-26
for i in {0..2048}; do kubectl -n velero-azure-issue-26 create configmap padding-$i --from-file padding.txt; done
```

This creates ~512MB of configmaps on a cluster (takes a while to run if the apiserver isn't on localhost). Note that excess random data is needed to prevent Velero from shrinking the upload below 256MiB through compression.

With the above configmaps present, plugin 1.0.0 fails to create backups while the patch works. Unfortunately there aren't any reproducible error logs in Velero when the backup fails- not sure why.

File: velero-plugin-for-microsoft-azure/object_store.go [hunk 1]
```diff
@@ -244,7 +249,52 @@ func (o *ObjectStore) PutObject(bucket, key string, body io.Reader) error {
...
-	return errors.WithStack(blob.CreateBlockBlobFromReader(body, nil))
+	// Azure requires a blob/object to be chunked if it's larger than 256MB. Since we
+	// don't know ahead of time if the body is over this limit or not, and it would
+	// require reading the entire object into memory to determine the size, we use the
+	// chunking approach for all objects.
+
+	var (
+		// blocks must be less than/equal to 100MB in size
+		// ref. https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#uri-parameters
+		block    = make([]byte, 100*1024*1024)
```
Comment (skriss) [inline velero-plugin-for-microsoft-azure/object_store.go]: we may want to make the block size (a) smaller by default to minimize memory usage, and (b) configurable.

Comment (dharmab) [reply velero-plugin-for-microsoft-azure/object_store.go]: Fair, although 100MiB of ECC memory costs something like 50 cents these days (not per month- that's the purchase price).

**Comment by skriss** [comment]
alright, this is ready for review from other maintainers.

For anyone following, I pushed a new image, `steveheptio/velero-plugin-for-microsoft-azure:chunk-objects-final`, containing the current version of the code that allows the block/chunk size to be optionally configured via the `BackupStorageLocation's` `config.blockSizeInBytes` field. It still defaults to 100MB.

**Comment by skriss** [comment]
@carlisia @nrb @ashish-amarnath gentle reminder that this needs some review, 🙏

File: velero-plugin-for-microsoft-azure/object_store.go [hunk 2]
```diff
@@ -235,16 +248,82 @@ func (o *ObjectStore) Init(config map[string]string) error {
...
+		if err == io.EOF {
+			break
+		}
+		// any other error: bubble it up
+		if err != nil {
+			return errors.Wrap(err, "error reading block from body")
+		}
+	}
+
+	o.log.Debugf("Putting block list %v", blockIDs)
```
Comment (ashish-amarnath) [inline velero-plugin-for-microsoft-azure/object_store.go]: Out of curiosity.. if  our app crashes before doing this. I assume there is no way to recover from it and the blob store will hold on to our blocks that we put for sometime discard them if it doesn't receive a `PutBlockList` call.

Comment (ashish-amarnath) [reply velero-plugin-for-microsoft-azure/object_store.go]: the other question would be: what's the max allowed time between all the `PutBlocks` and the `PutBlockList`?
Should the plugin be concerned with that?

Comment (skriss) [reply velero-plugin-for-microsoft-azure/object_store.go]: This is the best reference I've found for how it works: https://docs.microsoft.com/en-us/rest/api/storageservices/put-block#remarks

Specifically: "The block or blocks that you uploaded are not committed until you call Put Block List on the new blob. A blob created this way is maintained on the server for a week; if you have not added more blocks or committed blocks to the blob within that time period, then the blob is garbage collected."

File: backupstoragelocation.md [hunk 3]
```diff
@@ -40,4 +40,11 @@ spec:
     #
     # Optional.
     subscriptionId: my-subscription
+
+    # The block size, in bytes, to use when uploading objects to Azure blob storage.
+    # See https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-block-blobs--append-blobs--and-page-blobs#about-block-blobs
+    # for more information on block blobs.
+    # 
+    # Optional (defaults to 104857600, i.e. 100MB).
+    blockSizeInBytes: "10485760"
```
Comment (carlisia) [inline backupstoragelocation.md]: Should the value here be "104857600"? I think 10485760 corresponds to 10MB.

Comment (skriss) [reply backupstoragelocation.md]: Yeah, I put a non-default value in here since the field is not required if you just want the default. I could put something totally different (e.g. 1024) so it's not confusing

Comment (carlisia) [reply backupstoragelocation.md]: Ahhhhhhh. Could it be left blank?

Comment (skriss) [reply backupstoragelocation.md]: eh, I'll just put the default value in. I'd like to have a sample value.

Comment (carlisia) [reply backupstoragelocation.md]: Yes, that's good too.

Comment (skriss) [reply backupstoragelocation.md]: Updated.
